"""Constants used by the MongoDB connection layer."""

DEFAULT_MONGODB_HOST = "localhost:27017"
DEFAULT_DATABASE_NAME = "stintflow"
CONNECTION_TIMEOUT_MS = 5000
SERVER_SELECTION_TIMEOUT_MS = 5000
MAX_POOL_SIZE = 10
